### ISSUE TITLE
An improvement for Chapter 01

### ISSUE THREAD

**Issue by cye18** [xieliaing/CausalInferenceIntro#1]
Thanks for the great work you have done. It helps me a lot in understanding the book better.

In [Chapter 01](https://github.com/xieliaing/CausalInferenceIntro/blob/22a610efe618ddc16e74ede3ecc9132ea98c8786/chapters/01%20%E7%AC%AC%E4%B8%80%E7%AB%A0-%E5%9B%A0%E6%9E%9C%E5%85%B3%E7%B3%BB%E5%85%A5%E9%97%A8.ipynb), there is a sentence "也就是说，有能力为孩子提供平板电脑的学校比那些不能，不管药片如何处理" that appears to be unintelligible. It coule be "也就是说，有能力为孩子提供平板电脑的学校比那些不能的学校更好，无论它们是否提供平板电脑".

I couldn't get a url directly linking to the sentence, but if you search it, you should be able to easily find it.

**Comment by xieliaing** [comment]
Thank you for pointing that out. I think it was due to miss-aligned sentence when I was doing the translation. I will push the fix soon.

**Comment by xieliaing** [comment]
fix pushed, together with standardization of some terms

[commit 7e8ec0b4421dc25a273c1bfa966ce62bf8ea6a2a](https://github.com/xieliaing/CausalInferenceIntro/commit/7e8ec0b4421dc25a273c1bfa966ce62bf8ea6a2a)
