### ISSUE TITLE
请问第二十章的这个包在哪里下载呀

### ISSUE THREAD

**Issue by BlackTornadofrom1999** [xieliaing/CausalInferenceIntro#10]
from nb21 import cumulative_gain, elast 

pip install nb21 显示：
ERROR: Could not find a version that satisfies the requirement nb21 (from versions: none)
ERROR: No matching distribution found for nb21

**Comment by BlackTornadofrom1999** [comment]
额，我想我找到了。https://github.com/RobertMelika/ML-S-T-DR-CATE-Resp-Care/blob/main/nb21.py

**Comment by xieliaing** [comment]
在原作者的github里面也有：https://github.com/matheusfacure/python-causality-handbook/blob/master/causal-inference-for-the-brave-and-true/nb21.py

不过很高兴你自己也找到了可用的。

**Comment by BlackTornadofrom1999** [comment]
哇 谢谢！



---- 回复的原邮件 ----
| 发件人 | Liang ***@***.***> |
| 日期 | 2024年07月30日 23:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xieliaing/CausalInferenceIntro] 请问第二十章的这个包在哪里下载呀 (Issue #10) |

Closed #10 as completed.
