### ISSUE TITLE
请问有该书的中文翻译版pdf吗

### ISSUE THREAD

**Issue by bruno686** [xieliaing/CausalInferenceIntro#5]

**Comment by xieliaing** [comment]
as far as I know, there is no PDF version of Chinese translation.

**Comment by xieliaing** [comment]
The Jupyter Notebook has an option to export the notebook to PDF by clicking File -> Download as -> PDF via LaTeX (or PDF via HTML). Alternatively, you can use nbconvert to programmatically export notebook to PDF files.

**Comment by bruno686** [comment]
That's alright, Thank you very much!

**Comment by xieliaing** [comment]
you are welcome. close the issue.
