### ISSUE TITLE
Chapter 04 has several problems when displaying Chinese texts in notebook (so do the following chapters)

### ISSUE THREAD

**Issue by Youth-49** [xieliaing/CausalInferenceIntro#6]
the notebook seems to have problems with showing graphs with Chinese texts (Unicode-like strings are displayed).

**Comment by xieliaing** [comment]
I will check during weekend

**Comment by xieliaing** [comment]
Can you check the default encoding in your jupyter notebook:

import sys
sys.getdefaultencoding() 

Mine shows 'utf-8'

**Comment by Youth-49** [comment]
Thanks for reply.

I found this problem in previewing the Github webpages. (I didn't download the .ipynb files before)

I downloaded these .ipynb files in my laptop and found they are well-displayed.

Maybe it's related to setting of the previewing in Github. I don't think it is a problem for me now. LOL

**Comment by xieliaing** [comment]
Thanks for the update. That makes sense. Close the ticket.
