### ISSUE TITLE
the translate error of chapter 04

### ISSUE THREAD

**Issue by RogerMonkey** [xieliaing/CausalInferenceIntro#7]
I found that there are translate error in chapter 04 p1.2.  
the origin text show's that. 
> "As a general rule, the dependence flow in the direct path from A to C is blocked when we condition on an intermediary variable B"    

but the translated text is   

> "作为一般规则，当我们以中间变量 C 为条件时，从 A 到 B 的直接路径中的依赖流被阻塞。"  

In fact the intermediary variable is B rather than C.

**Comment by xieliaing** [comment]
I saw you fixed it. Merged the PR

**Comment by xieliaing** [comment]
fix merged
